### ISSUE TITLE
ERROR: tensorflow-1.4.0rc0-cp35-cp35m-linux_aarch64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by liubq7** [noahzhy/tf-aarch64#1]
Hi!

I'm trying to install tensorflow 1.x but I kept receiving error "is not a supported wheel on this platform".

My OS: Ubuntu 18.04.6
gcc: 7.5.0
CPU:
```
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           4
Vendor ID:           Nvidia
Model:               0
Model name:          ARMv8 Processor rev 0 (v8l)
Stepping:            0x0
CPU max MHz:         2265,6001
CPU min MHz:         115,2000
BogoMIPS:            62.50
L1d cache:           64K
L1i cache:           128K
L2 cache:            2048K
L3 cache:            4096K
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp
```
I tried python 3.6 and 2.7, inside as well as outside virtual environment, all report the same error. Should I use other kinds of whl?

**Comment by noahzhy** [comment]
Wait a second, let me upload some new version tf 1.x .whl files.

**Comment by noahzhy** [comment]
@liubq7 try the tf version 1.15.5 with python 3.6 or 3.7

**Comment by liubq7** [comment]
Hi, I need tf >= 1.4, and it would be better if I can install by py2.7
(just realize cp35 indicates the python version, no wonder it reports error 😅

**Comment by noahzhy** [comment]
Py 2.7 is too old for tf and other supported third part libs. The version 1.14, 1.15 is very newest version for tf 1.x. Maybe you could try tf 2.x, it supports many aarch64 devices now.

**Comment by liubq7** [comment]
Thank you very much, will have a try!
